name: 'HEMTT'
description: 'Build project with HEMTT'
author: 'HEMTT'
branding:
  icon: 'truck'  
  color: 'green'
inputs: 
  version:
    description: 'HEMTT Version'
    default: 'latest'
  annotate:
    description: 'Annotate output'
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: 'always()'
